//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProyectoFinal.ws_Hotel {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsHotelSoap", Namespace="http://tempuri.org/")]
    public partial class wsHotel : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback Met_HospedajeOperationCompleted;
        
        private System.Threading.SendOrPostCallback Met_AlimentacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Met_ImpuestosOperationCompleted;
        
        private System.Threading.SendOrPostCallback Met_TotalOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsHotel() {
            this.Url = global::ProyectoFinal.Properties.Settings.Default.ProyectoFinal_ws_Hotel_wsHotel;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event Met_HospedajeCompletedEventHandler Met_HospedajeCompleted;
        
        /// <remarks/>
        public event Met_AlimentacionCompletedEventHandler Met_AlimentacionCompleted;
        
        /// <remarks/>
        public event Met_ImpuestosCompletedEventHandler Met_ImpuestosCompleted;
        
        /// <remarks/>
        public event Met_TotalCompletedEventHandler Met_TotalCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Hospedaje", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Met_Hospedaje(int FechaSMes, int Dias, int Ninos, int adultos, double Tarifa) {
            object[] results = this.Invoke("Met_Hospedaje", new object[] {
                        FechaSMes,
                        Dias,
                        Ninos,
                        adultos,
                        Tarifa});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Met_HospedajeAsync(int FechaSMes, int Dias, int Ninos, int adultos, double Tarifa) {
            this.Met_HospedajeAsync(FechaSMes, Dias, Ninos, adultos, Tarifa, null);
        }
        
        /// <remarks/>
        public void Met_HospedajeAsync(int FechaSMes, int Dias, int Ninos, int adultos, double Tarifa, object userState) {
            if ((this.Met_HospedajeOperationCompleted == null)) {
                this.Met_HospedajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMet_HospedajeOperationCompleted);
            }
            this.InvokeAsync("Met_Hospedaje", new object[] {
                        FechaSMes,
                        Dias,
                        Ninos,
                        adultos,
                        Tarifa}, this.Met_HospedajeOperationCompleted, userState);
        }
        
        private void OnMet_HospedajeOperationCompleted(object arg) {
            if ((this.Met_HospedajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Met_HospedajeCompleted(this, new Met_HospedajeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Alimentacion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Met_Alimentacion(int TipoA, double Hospedaje) {
            object[] results = this.Invoke("Met_Alimentacion", new object[] {
                        TipoA,
                        Hospedaje});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Met_AlimentacionAsync(int TipoA, double Hospedaje) {
            this.Met_AlimentacionAsync(TipoA, Hospedaje, null);
        }
        
        /// <remarks/>
        public void Met_AlimentacionAsync(int TipoA, double Hospedaje, object userState) {
            if ((this.Met_AlimentacionOperationCompleted == null)) {
                this.Met_AlimentacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMet_AlimentacionOperationCompleted);
            }
            this.InvokeAsync("Met_Alimentacion", new object[] {
                        TipoA,
                        Hospedaje}, this.Met_AlimentacionOperationCompleted, userState);
        }
        
        private void OnMet_AlimentacionOperationCompleted(object arg) {
            if ((this.Met_AlimentacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Met_AlimentacionCompleted(this, new Met_AlimentacionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Impuestos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Met_Impuestos(double Hospedaje, double Alimentacion) {
            object[] results = this.Invoke("Met_Impuestos", new object[] {
                        Hospedaje,
                        Alimentacion});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Met_ImpuestosAsync(double Hospedaje, double Alimentacion) {
            this.Met_ImpuestosAsync(Hospedaje, Alimentacion, null);
        }
        
        /// <remarks/>
        public void Met_ImpuestosAsync(double Hospedaje, double Alimentacion, object userState) {
            if ((this.Met_ImpuestosOperationCompleted == null)) {
                this.Met_ImpuestosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMet_ImpuestosOperationCompleted);
            }
            this.InvokeAsync("Met_Impuestos", new object[] {
                        Hospedaje,
                        Alimentacion}, this.Met_ImpuestosOperationCompleted, userState);
        }
        
        private void OnMet_ImpuestosOperationCompleted(object arg) {
            if ((this.Met_ImpuestosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Met_ImpuestosCompleted(this, new Met_ImpuestosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Met_Total", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public double Met_Total(double Hospedaje, double Alimentacion, double Impuestos) {
            object[] results = this.Invoke("Met_Total", new object[] {
                        Hospedaje,
                        Alimentacion,
                        Impuestos});
            return ((double)(results[0]));
        }
        
        /// <remarks/>
        public void Met_TotalAsync(double Hospedaje, double Alimentacion, double Impuestos) {
            this.Met_TotalAsync(Hospedaje, Alimentacion, Impuestos, null);
        }
        
        /// <remarks/>
        public void Met_TotalAsync(double Hospedaje, double Alimentacion, double Impuestos, object userState) {
            if ((this.Met_TotalOperationCompleted == null)) {
                this.Met_TotalOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMet_TotalOperationCompleted);
            }
            this.InvokeAsync("Met_Total", new object[] {
                        Hospedaje,
                        Alimentacion,
                        Impuestos}, this.Met_TotalOperationCompleted, userState);
        }
        
        private void OnMet_TotalOperationCompleted(object arg) {
            if ((this.Met_TotalCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Met_TotalCompleted(this, new Met_TotalCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Met_HospedajeCompletedEventHandler(object sender, Met_HospedajeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Met_HospedajeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Met_HospedajeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Met_AlimentacionCompletedEventHandler(object sender, Met_AlimentacionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Met_AlimentacionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Met_AlimentacionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Met_ImpuestosCompletedEventHandler(object sender, Met_ImpuestosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Met_ImpuestosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Met_ImpuestosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void Met_TotalCompletedEventHandler(object sender, Met_TotalCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Met_TotalCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Met_TotalCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public double Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((double)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591